### ISSUE TITLE
apko crashes badly without HOME env variable

### ISSUE THREAD

**Issue by sfc-gh-ptabor** [chainguard-dev/apko#788]
`apko` does not tolerate lack of HOME (env):

```
$env - ./apko build ../../chainguard-images/images/bazel/configs/latest.apko.yaml foo bar.tar
```

produces:

```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100ec939c]

goroutine 9 [running]:
github.com/chainguard-dev/go-apk/pkg/apk.(*APK).InitDB(0x0, {0x101930018, 0x1400003c038}, {0x1021640c8, 0x0, 0x0})
	github.com/chainguard-dev/go-apk@v0.0.0-20230628205940-516bb829d27b/pkg/apk/implementation.go:203 +0x3c
chainguard.dev/apko/pkg/apk.(*APK).Initialize(0x14000286000, 0x14000146a88)
	chainguard.dev/apko/pkg/apk/apk.go:80 +0x78
chainguard.dev/apko/pkg/build.(*buildImplementation).InitializeApk(0x1400009d080?, {0x10193b370?, 0x14000232000?}, 0x140003b8020?, 0x140003640f0?)
	chainguard.dev/apko/pkg/build/build_implementation.go:199 +0xa4
chainguard.dev/apko/pkg/build.buildImage({0x10193b370, 0x14000232000}, 0x0?, 0x14000146c90, 0x0?, 0x7000104?)
	chainguard.dev/apko/pkg/build/build_implementation.go:266 +0x164
chainguard.dev/apko/pkg/build.(*Context).BuildImage(0x14000146a80)
	chainguard.dev/apko/pkg/build/build.go:122 +0x48
chainguard.dev/apko/pkg/build.(*Context).BuildLayer(0x1400050ebf0?)
	chainguard.dev/apko/pkg/build/build.go:156 +0x28
chainguard.dev/apko/internal/cli.buildImageComponents.func1()
	chainguard.dev/apko/internal/cli/build.go:273 +0x1fc
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa0
```

**Comment by sfc-gh-ptabor** [comment]
(seems like logger is not being initialized, but I might be wrong).

**Comment by deitch** [comment]
Fixed in #796. This really should not have crashed, it should have reported an error. `HOME` is required for the caching to work.

**Comment by kaniini** [comment]
Should we not just disable caching if `HOME` is unset then?

**Comment by deitch** [comment]
We can do that as well. First thing was to get an error instead of crashing, which is done. We can add that next step. Should be coming shortly.
